import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Backend Best Practices | Eduardo Melo",
  description: "Thoughts on architecture and clean code.",
};

export default function BlogPost() {
  return (
    <div className="space-y-12">
      
      <Link 
        href="/lab" 
        className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-black dark:hover:text-white transition-colors no-underline"
      >
        <ArrowLeft size={16} /> Back to Lab
      </Link>

      <article className="space-y-10">
        
        <header className="space-y-4">
          <h1 className="text-2xl font-bold text-black dark:text-white">
            Best Practices for Backend Developers
          </h1>
          <div className="flex gap-4 text-xs text-gray-400 font-mono">
          </div>
          <p className="text-lg text-gray-600 dark:text-gray-300 leading-relaxed pt-2">
            Deliver value with clean code. Here are some thoughts on my journey building robust APIs.
          </p>
        </header>

        <div className="space-y-8 text-gray-700 dark:text-gray-400 leading-relaxed">
          
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-black dark:text-white">Architecture & Organization</h2>
            <p>
              You can't scale a system if you mix business rules in the Controller or the Database. 
              A good rule is to keep the separation of concerns sacred: Controller talks to the outside world, 
              Service holds the logic, Repository talks to the data.
            </p>
            <div className="bg-gray-100 dark:bg-gray-900 p-4 rounded-lg border-l-4 border-blue-500 text-sm">
              <span className="font-bold text-black dark:text-white block mb-1">👉 Tip</span>
              Study <strong>Clean Architecture</strong> or Hexagonal. Decoupling facilitates testing and future maintenance.
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-black dark:text-white">API Design (RESTful)</h2>
            <p>
              Avoid endpoints with inconsistent verbs or structures. Standardize your returns and use 
              <strong> HTTP Status Codes</strong> correctly (201 for created, 404 for not found, 400 for client error). 
              The API contract must be predictable.
            </p>
            <div className="bg-gray-100 dark:bg-gray-900 p-4 rounded-lg border-l-4 border-blue-500 text-sm">
              <span className="font-bold text-black dark:text-white block mb-1">👉 Tip</span>
              Use <strong>DTOs (Data Transfer Objects)</strong>. Never expose your persistence Entities (JPA) directly in the API response.
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-black dark:text-white">Logs & Error Handling</h2>
            <p>
              Don't leave the API consumer in the dark with a generic "Internal Server Error", nor pollute your console with useless logs. 
              Keep error messages clear, informative, and safe. Small details in logs save lives in production.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-black dark:text-white">Performance & Database</h2>
            <p>
              Using an ORM (like Hibernate) makes things easier, but it can be a trap if you don't understand what happens "under the hood". 
              Avoid the <strong>N+1</strong> query problem and create indexes for the most searched columns.
            </p>
            <div className="bg-gray-100 dark:bg-gray-900 p-4 rounded-lg border-l-4 border-blue-500 text-sm">
              <span className="font-bold text-black dark:text-white block mb-1">👉 Tip</span>
              Always analyze the SQL queries generated by your code. Performance is a feature.
            </div>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          <p className="italic text-sm">
            These are points I've noticed make a difference in day-to-day work. Start simple and evolve complexity as needed.
          </p>

        </div>

      </article>
    </div>
  );
}